# Generated by Django 5.0.4 on 2024-05-09 18:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_customer_created_at_alter_customer_id_and_more'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=60)),
                ('total_amount', models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.SmallIntegerField(choices=[(0, 'Completed'), (1, 'Rejected')], default=0)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLoanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
            ],
        ),
    ]
