# Generated by Django 5.0.4 on 2024-05-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentloandetail',
            unique_together={('loan_id', 'payment_id')},
        ),
    ]
