# Generated by Django 5.0.4 on 2024-05-09 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_customer_id_loan_customer'),
        ('payments', '0002_alter_paymentloandetail_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentloandetail',
            old_name='loan_id',
            new_name='loan',
        ),
        migrations.RenameField(
            model_name='paymentloandetail',
            old_name='payment_id',
            new_name='payment',
        ),
        migrations.AlterUniqueTogether(
            name='paymentloandetail',
            unique_together={('loan', 'payment')},
        ),
    ]
