# Generated by Django 5.0.4 on 2024-05-10 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_external_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
