# Generated by Django 5.0.4 on 2024-05-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_customer_id_payment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Completed'), (2, 'Rejected')], default=1),
        ),
    ]
