# Generated by Django 5.0.4 on 2024-05-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_customer_id_loan_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='external_id',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
